### ISSUE TITLE
날리다 이야기

### ISSUE THREAD

**Issue by inmoonlight** [nalida-dev/nalida.info#14]
샘플 포스팅

**Comment by inmoonlight** [comment]
태그 리스트 형식으로

**Comment by inmoonlight** [comment]
브런치 스타일

**Comment by inmoonlight** [comment]
![image](https://user-images.githubusercontent.com/24843996/51784002-f964a380-2185-11e9-889f-2d0df6f08388.png)
이런식으로

**Comment by mwnlkhlee** [comment]
추후 다른 이슈가 생기면 마일스톤으로 둘 것
