### ISSUE TITLE
소개

### ISSUE THREAD

**Issue by inmoonlight** [nalida-dev/nalida.info#15]
날리다 classic
  날리다 color
  날리다 같혼여
  날리다 portable (날리냥)
  날리다 월드 (일본)

**Comment by inmoonlight** [comment]
참고 페이지: https://munto.kr/about

**Comment by inmoonlight** [comment]
날리다 월드는 구글 이미지로

**Comment by inmoonlight** [comment]
- 날리다 기타 프로젝트 (허니번 등)

**Comment by mwnlkhlee** [comment]
마일스톤으로 둘 것
