### ISSUE TITLE
이미지 사이즈 관련 수정 사항

### ISSUE THREAD

**Issue by inmoonlight** [nalida-dev/nalida.info#30]
- [x] 소개, 날리다 이야기 대표 이미지 바꾸기
- [x] 소개에 기타 프로젝트 추가

**Comment by inmoonlight** [comment]
- [ ] 날리다 이야기 카드 max height 에 같은 줄에 있는 모든 카드 height 맞추기
- [ ] 워크샵 소개 이미지 사이즈 통일 및 카드 뷰

**Comment by mwnlkhlee** [comment]
소개 페이지와 날리다 이야기 페이지의 사진 높이 통일
