### ISSUE TITLE
모바일 환경 대응

### ISSUE THREAD

**Issue by mwnlkhlee** [nalida-dev/nalida.info#41]
- [ ] 대문 사진 크기 바뀌는 현상 해결

- [ ] 캘린더가 달력 형태로 나오지 않는 현상 해결

- [ ] 글씨 크기 조절, 특히 태그

**Comment by inmoonlight** [comment]
### TO-BE

<img src="https://user-images.githubusercontent.com/24843996/52530663-16839f80-2d4c-11e9-9021-f1ee018d0cc2.png" width=50%>

**Comment by mwnlkhlee** [comment]
항목별로 나누어 이슈를 따로 만들었습니다.
